title: Madison Avenue Radio
description: >- # this means to ignore newlines until "baseurl:"
  Ramblings from the Wright household.
url: "http://pod.joejag.com" # the base hostname & protocol for your site, e.g. http://example.com

author: "Joe Wright"
email: "joe@joejag.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
