title: Madison Avenue Radio
description: >- # this means to ignore newlines until "baseurl:"
  Ramblings from the Wright household.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author: "Joe Wright"
email: "joe@joejag.com"

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
